### ISSUE TITLE
Long pause at rest position

### ISSUE THREAD

**Issue by Shadowen** [yschaeff/slic3r_post_processing#1]
Is it possible to reduce the amount of time the extruder spends at the rest position? My printer is idling for ~10 seconds at the rest position and the ooze is fairly bad. I think this is caused by you filling the buffer with no-ops (not really sure). Any advice?

**Comment by yschaeff** [comment]
Yeah sounds like your printer is waiting 1 second per nop. It should be waiting 1 milisecond though. Maybe a firmware bug? Try removing this line:
  for i in range(10): pre += "G4 P1; Filling print queue\n"

It could be that your timelaspses become jittery if you do that. so alternatively replace the "G4 P1" with something like "G1" without arguments. Hopefully this is accepted by your printer as move nothing move.
Please let me know what works.

**Comment by Shadowen** [comment]
It's a FlashForge Creator Pro running Sailfish 7.7. I'll try messing with the no-op command to see if I can get it to respond faster tomorrow. Thanks for your help - I'll keep you updated.

**Comment by Shadowen** [comment]
Seems to work great but I'm still having trouble with oozing. Will look into my retraction settings later. Thanks!

**Comment by yschaeff** [comment]
So to be clear you changed the "G4 P1" command to "G1"? If that works I'll update the code on github.

**Comment by Shadowen** [comment]
Hey, sorry for the delay.

I have:
`for i in range(10): pre += "G1; Filling print queue\n"`

It works fine (except for the oozing).
